name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t smz/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true smz/react-test npm test

      - run: docker build -t smz/multi-client ./client
      - run: docker build -t smz/multi-nginx ./nginx
      - run: docker build -t smz/multi-server ./server
      - run: docker build -t smz/multi-worker ./worker

      - run: docker tag multi-client smz/multi-client
      - run: docker tag multi-nginx smz/multi-nginx
      - run: docker tag multi-server smz/multi-server
      - run: docker tag multi-worker smz/multi-worker

      - run: docker push smz/multi-client
      - run: docker push smz/multi-nginx
      - run: docker push smz/multi-server
      - run: docker push smz/multi-worker
